"""
Architecture Diagram Generator
Generates a Mermaid flowchart of the full agent pipeline.
Output: docs/architecture.md  (Mermaid-renderable)

Displayed in the Gradio UI sidebar and included in the submission write-up.
This is one of the specific things Microsoft and Google hackathon judges score.

Run standalone:   python modules/diagram.py
Or via Makefile:  make diagram
"""

from pathlib import Path
from rich.console import Console
from rich.panel import Panel

console = Console()

DOCS_DIR = Path(__file__).parent.parent / "docs"


def generate_diagram(specialists: list[str] | None = None) -> str:
    """Generate a Mermaid flowchart. specialists = list of specialist agent names."""

    if not specialists:
        try:
            from agent.specialists import SPECIALISTS
            specialists = [s.name for s in SPECIALISTS]
        except ImportError:
            specialists = ["general"]

    specialist_nodes = "\n".join(
        f'    Spec{i}["{name.replace("_", " ").title()} Agent"]'
        for i, name in enumerate(specialists)
    )
    specialist_edges_in = "\n".join(
        f"    Router --> Spec{i}"
        for i in range(len(specialists))
    )
    specialist_edges_out = "\n".join(
        f"    Spec{i} --> Aggregator"
        for i in range(len(specialists))
    )

    mermaid = f"""```mermaid
flowchart TD
    User([User Input]) --> UI[Gradio UI / CLI]
    UI --> Memory[(ChromaDB Memory)]
    Memory -->|context hint| Orchestrator

    UI --> Orchestrator[Orchestrator Agent]
    Orchestrator --> Router{{Task Router}}

{specialist_nodes}

{specialist_edges_in}
{specialist_edges_out}

    Aggregator[Aggregator] --> Validator[Meta-Validator Agent]

    Validator -->|PASS| Output([Final Answer])
    Validator -->|FAIL| Reflexion[Reflexion Loop]
    Reflexion -->|feedback + retry| Orchestrator

    Output --> Logger[(JSON Log)]
    Output --> PhoenixObs[(Arize Phoenix Traces)]
    Output --> MemStore[(Store to Memory)]

    style Orchestrator fill:#4A90D9,color:#fff
    style Router fill:#7B68EE,color:#fff
    style Validator fill:#E67E22,color:#fff
    style Reflexion fill:#E74C3C,color:#fff
    style Memory fill:#27AE60,color:#fff
    style PhoenixObs fill:#2ECC71,color:#fff
    style Logger fill:#95A5A6,color:#fff
```"""

    return mermaid


def write_diagram(specialists: list[str] | None = None) -> Path:
    DOCS_DIR.mkdir(exist_ok=True)
    diagram = generate_diagram(specialists)

    content = f"""# Agent Architecture

Auto-generated by `modules/diagram.py`.

## Full Pipeline

{diagram}

## Component Descriptions

| Component | Role |
|---|---|
| **Gradio UI** | Demo interface — localhost:7860 |
| **Orchestrator** | Receives task, decides specialist routing |
| **Task Router** | Routes subtasks to specialists based on domain |
| **Specialist Agents** | Domain-focused agents with targeted tools |
| **Aggregator** | Merges specialist results into one answer |
| **Meta-Validator** | Independent agent that fact-checks the answer |
| **Reflexion Loop** | Self-correction: retries if validator fails (max {3} loops) |
| **ChromaDB Memory** | Long-term memory — injects relevant past runs as context |
| **Arize Phoenix** | OpenTelemetry traces — every LLM + tool call logged |
| **JSON Logs** | Audit trail in `logs/` — every run persisted |

## Stack

- **Framework**: PydanticAI
- **Observability**: Arize Phoenix (OpenTelemetry)
- **Prompt Management**: Langfuse + local YAML versioning
- **Memory**: ChromaDB (semantic similarity retrieval)
- **Evaluation**: DeepEval (TaskCompletion, AnswerRelevancy, Hallucination)
"""

    out_path = DOCS_DIR / "architecture.md"
    out_path.write_text(content)
    console.print(f"[green]Architecture diagram written →[/green] {out_path}")
    return out_path


if __name__ == "__main__":
    console.print(Panel("[bold cyan]Generating Architecture Diagram[/bold cyan]"))
    path = write_diagram()
    console.print("\n[bold]Mermaid diagram preview:[/bold]")
    console.print(generate_diagram())
    console.print(f"\nOpen [cyan]{path}[/cyan] or paste the Mermaid block into https://mermaid.live")
