"""
Main agent entry point.
Stack: PydanticAI + Arize Phoenix (observability) + Langfuse (prompt versioning) + Reflexion

Run:
    python agent/agent.py
    python agent/agent.py --input "your task here"

Phoenix dashboard: http://localhost:6006 (auto-opens when agent runs)
"""

import os
import sys
import asyncio
import argparse
import yaml
from pathlib import Path
from typing import Any
from pydantic import BaseModel
from pydantic_ai import Agent
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
from dotenv import load_dotenv

load_dotenv()
sys.path.insert(0, str(Path(__file__).parent.parent))

from agent.config import (
    MODEL, MAX_REFLECTIONS, REFLECTION_THRESHOLD,
    PHOENIX_ENABLED, PHOENIX_PORT,
    PROMPTS_DIR, ACTIVE_PROMPT_VERSION, LANGFUSE_ENABLED,
)

console = Console()


# ── Observability setup (Phoenix) ─────────────────────────────────────────────

def setup_observability() -> None:
    if not PHOENIX_ENABLED:
        return
    try:
        import phoenix as px
        from openinference.instrumentation.anthropic import AnthropicInstrumentor
        px.launch_app(port=PHOENIX_PORT)
        AnthropicInstrumentor().instrument()
        console.print(f"[green]Phoenix tracing active →[/green] http://localhost:{PHOENIX_PORT}")
    except ImportError:
        console.print("[yellow]Phoenix not installed — skipping observability. Run: pip install arize-phoenix[/yellow]")


# ── Prompt management ─────────────────────────────────────────────────────────

def load_system_prompt(version: str = ACTIVE_PROMPT_VERSION) -> str:
    """Load system prompt. Langfuse takes priority; falls back to local YAML."""
    if LANGFUSE_ENABLED:
        try:
            from langfuse import Langfuse
            lf = Langfuse()
            prompt_obj = lf.get_prompt("system-prompt")
            console.print(f"[green]Prompt loaded from Langfuse[/green] (version {prompt_obj.version})")
            return prompt_obj.compile()
        except Exception as e:
            console.print(f"[yellow]Langfuse prompt fetch failed ({e}), falling back to local YAML[/yellow]")

    prompt_file = PROMPTS_DIR / f"system_v{version}.yaml"
    if not prompt_file.exists():
        console.print(f"[red]Prompt file not found: {prompt_file}[/red]")
        console.print("[yellow]Run the full pipeline first: python runner.py[/yellow]")
        sys.exit(1)

    with open(prompt_file) as f:
        data = yaml.safe_load(f)
    console.print(f"[green]Prompt loaded from local YAML[/green] (v{data['version']})")
    return data["prompt"]


# ── Structured output model ────────────────────────────────────────────────────
# Replace with your problem-specific output schema after scaffold generates tools.

class AgentAnswer(BaseModel):
    answer: str
    reasoning: str
    confidence: float   # 0.0 – 1.0
    tools_used: list[str]


# ── Agent definition ───────────────────────────────────────────────────────────

def build_agent(system_prompt: str) -> Agent:
    from agent.tools import TOOLS  # generated by scaffold on question drop

    agent: Agent[None, AgentAnswer] = Agent(
        model=f"anthropic:{MODEL}",
        result_type=AgentAnswer,
        system_prompt=system_prompt,
    )

    for tool_fn in TOOLS:
        agent.tool(tool_fn)

    return agent


# ── Reflexion loop ─────────────────────────────────────────────────────────────

async def _score_result(result: AgentAnswer, task: str) -> tuple[float, str]:
    """Quick LLM-based scoring. DeepEval does the full eval; this drives Reflexion."""
    try:
        import anthropic as anth
        client = anth.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        resp = client.messages.create(
            model=MODEL,
            max_tokens=200,
            messages=[{
                "role": "user",
                "content": (
                    f"Task: {task}\n\n"
                    f"Agent answer: {result.answer}\n\n"
                    f"Rate this answer from 0.0 to 1.0. "
                    f"Reply with ONLY: <score>|<one sentence reason>. Example: 0.82|The answer addresses the core task."
                )
            }]
        )
        parts = resp.content[0].text.strip().split("|", 1)
        score = float(parts[0].strip())
        reason = parts[1].strip() if len(parts) > 1 else "No reason given"
        return score, reason
    except Exception:
        return result.confidence, "Score derived from agent confidence"


async def run_with_reflection(agent: Agent, task: str) -> AgentAnswer:
    feedback = ""
    best_result: AgentAnswer | None = None
    best_score = 0.0

    for attempt in range(1, MAX_REFLECTIONS + 1):
        input_text = task + feedback
        console.print(f"\n[bold]Attempt {attempt}/{MAX_REFLECTIONS}[/bold]")

        run_result = await agent.run(input_text)
        result: AgentAnswer = run_result.data

        score, reason = await _score_result(result, task)
        console.print(f"  Score: [{'green' if score >= REFLECTION_THRESHOLD else 'yellow'}]{score:.2f}[/] — {reason}")

        if score > best_score:
            best_score = score
            best_result = result

        if score >= REFLECTION_THRESHOLD:
            console.print(f"  [green]Passed threshold ({REFLECTION_THRESHOLD}). Accepting.[/green]")
            break

        if attempt < MAX_REFLECTIONS:
            feedback = (
                f"\n\n[Reflection {attempt}] Previous attempt scored {score:.2f}/1.0. "
                f"Reason: {reason}. Improve your answer, be more precise and complete."
            )
            console.print(f"  [yellow]Below threshold — reflecting and retrying...[/yellow]")

    return best_result


# ── Main ───────────────────────────────────────────────────────────────────────

async def main(task: str) -> AgentAnswer:
    setup_observability()

    system_prompt = load_system_prompt()
    agent = build_agent(system_prompt)

    console.print(Panel(
        f"[bold cyan]Running Agent[/bold cyan]\n[dim]{task[:200]}{'...' if len(task) > 200 else ''}[/dim]",
        border_style="cyan",
    ))

    result = await run_with_reflection(agent, task)

    console.print(Panel(
        f"[bold green]Answer[/bold green]\n\n{result.answer}\n\n"
        f"[dim]Reasoning: {result.reasoning}[/dim]\n"
        f"[dim]Confidence: {result.confidence:.0%} | Tools used: {', '.join(result.tools_used)}[/dim]",
        border_style="green",
    ))

    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=str, default="", help="Task input for the agent")
    args = parser.parse_args()

    task = args.input
    if not task:
        console.print("[red]Provide a task: python agent/agent.py --input 'your task here'[/red]")
        sys.exit(1)

    asyncio.run(main(task))
