"""
Multi-Agent Orchestrator
Pattern: Orchestrator routes task → specialist sub-agents → aggregator → validator

Architecture (auto-diagrammed by modules/diagram.py):
  User Input
      ↓
  Orchestrator  (decides which specialists are needed and in what order)
      ↓
  Task Router   (dispatches subtasks to specialist agents in parallel)
      ↓
  Specialist Agents  (each has focused tools + focused system prompt)
      ↓
  Aggregator    (merges specialist results into coherent answer)
      ↓
  Validator     (meta-agent checks answer before it leaves the system)

Specialist agents are generated by scaffold.py on question drop.
This file is the static orchestration framework — it never changes.
"""

import asyncio
import os
from dataclasses import dataclass
from pydantic import BaseModel
from pydantic_ai import Agent
from rich.console import Console

console = Console()


# ── Specialist definition ─────────────────────────────────────────────────────

@dataclass
class Specialist:
    name: str
    description: str       # what this specialist handles
    system_prompt: str
    tools: list            # list of tool functions


# ── Orchestrator output ───────────────────────────────────────────────────────

class RoutingDecision(BaseModel):
    subtasks: list[str]           # broken-down subtasks
    specialist_assignments: dict[str, str]  # specialist_name → subtask
    reasoning: str


class AggregatedAnswer(BaseModel):
    answer: str
    reasoning: str
    confidence: float
    tools_used: list[str]
    specialists_used: list[str]


# ── Core orchestrator ─────────────────────────────────────────────────────────

class MultiAgentOrchestrator:
    def __init__(self, model: str, specialists: list[Specialist]):
        self.model = model
        self.specialists = {s.name: s for s in specialists}
        self._seen_routes: set[str] = set()   # loop prevention

    def _build_specialist_agent(self, specialist: Specialist) -> Agent:
        agent: Agent[None, AggregatedAnswer] = Agent(
            model=f"anthropic:{self.model}",
            output_type=AggregatedAnswer,
            system_prompt=specialist.system_prompt,
        )
        for tool_fn in specialist.tools:
            agent.tool(tool_fn)
        return agent

    def _build_router_agent(self) -> Agent:
        specialist_list = "\n".join(
            f"- {name}: {s.description}"
            for name, s in self.specialists.items()
        )
        system = (
            "You are a task router for a multi-agent system.\n"
            f"Available specialists:\n{specialist_list}\n\n"
            "Break the user's task into subtasks and assign each to the most appropriate specialist. "
            "Each specialist should handle what they're best at. "
            "Return a routing decision with clear subtask assignments."
        )
        return Agent(
            model=f"anthropic:{self.model}",
            output_type=RoutingDecision,
            system_prompt=system,
        )

    def _build_aggregator_agent(self) -> Agent:
        system = (
            "You are an aggregator for a multi-agent system. "
            "You receive partial results from multiple specialist agents. "
            "Synthesize them into one coherent, complete, and accurate final answer. "
            "Do not add information not present in the specialist results."
        )
        return Agent(
            model=f"anthropic:{self.model}",
            output_type=AggregatedAnswer,
            system_prompt=system,
        )

    async def run(self, task: str) -> AggregatedAnswer:
        console.print(f"\n[bold cyan]Orchestrator[/bold cyan] → routing task across {len(self.specialists)} specialists")

        # ── Step 1: Route ─────────────────────────────────────────────────────
        router = self._build_router_agent()
        routing_result = await router.run(task)
        decision: RoutingDecision = routing_result.output

        console.print(f"  Subtasks: {len(decision.subtasks)}")
        console.print(f"  Routing: {decision.specialist_assignments}")

        # ── Step 2: Dispatch in parallel (loop prevention) ────────────────────
        async def run_specialist(name: str, subtask: str) -> AggregatedAnswer | None:
            route_key = f"{name}:{subtask[:80]}"
            if route_key in self._seen_routes:
                console.print(f"  [yellow]Loop detected: {name} already handled this — skipping[/yellow]")
                return None
            self._seen_routes.add(route_key)

            if name not in self.specialists:
                console.print(f"  [red]Unknown specialist: {name}[/red]")
                return None

            console.print(f"  [green]→ {name}[/green]: {subtask[:80]}")
            specialist = self.specialists[name]
            agent = self._build_specialist_agent(specialist)
            result = await agent.run(subtask)
            return result.output

        tasks = [
            run_specialist(name, subtask)
            for name, subtask in decision.specialist_assignments.items()
        ]
        specialist_results = await asyncio.gather(*tasks, return_exceptions=True)

        valid_results = [
            r for r in specialist_results
            if isinstance(r, AggregatedAnswer)
        ]

        if not valid_results:
            return AggregatedAnswer(
                answer="No specialist could handle the task.",
                reasoning="All specialist runs failed or were skipped.",
                confidence=0.0,
                tools_used=[],
                specialists_used=list(decision.specialist_assignments.keys()),
            )

        # ── Step 3: Aggregate ─────────────────────────────────────────────────
        if len(valid_results) == 1:
            result = valid_results[0]
            result.specialists_used = list(decision.specialist_assignments.keys())
            return result

        aggregator = self._build_aggregator_agent()
        combined = "\n\n".join(
            f"[{i+1}] {r.answer}" for i, r in enumerate(valid_results)
        )
        agg_result = await aggregator.run(
            f"Original task: {task}\n\nSpecialist results:\n{combined}"
        )
        final: AggregatedAnswer = agg_result.output
        final.specialists_used = list(decision.specialist_assignments.keys())
        final.tools_used = list({t for r in valid_results for t in r.tools_used})
        return final


# ── Specialist registry (populated by scaffold.py) ───────────────────────────
# scaffold.py writes SPECIALISTS = [...] into agent/specialists.py on question drop.
# This file imports it at runtime so no changes needed here.

def load_specialists() -> list[Specialist]:
    try:
        from agent.specialists import SPECIALISTS
        return SPECIALISTS
    except ImportError:
        # Fallback: single specialist using default tools (pre-question-drop)
        from agent.tools import TOOLS
        return [
            Specialist(
                name="general",
                description="Handles all tasks",
                system_prompt="You are a helpful AI agent. Use your tools to answer the task.",
                tools=TOOLS,
            )
        ]
